export const countryNameToCode = {
  "Antigua y Barbuda": "ag",
  Argentina: "ar",
  Bahamas: "bs",
  Barbados: "bb",
  Bolivia: "bo",
  Brasil: "br",
  Canadá: "ca",
  Chile: "cl",
  Colombia: "co",
  "Costa Rica": "cr",
  Cuba: "cu",
  Dominica: "dm",
  Ecuador: "ec",
  "Estados Unidos": "us",
  Granada: "gd",
  Guyana: "gy",
  Jamaica: "jm",
  México: "mx",
  Panamá: "pa",
  Perú: "pe",
  "República Dominicana": "do",
  Surinam: "sr",
  "Trinidad y Tobago": "tt",
  Uruguay: "uy",
  Venezuela: "ve",
};
