"""empty message

Revision ID: 02a789668507
Revises: f300b424dfb7
Create Date: 2024-09-17 20:11:51.299458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a789668507'
down_revision = 'f300b424dfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_added_beer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('bjcp_style', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('IBUs', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('volALC', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('picture_of_beer_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('brewery_id', sa.Integer(), nullable=True))
        batch_op.alter_column('bar_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'brewery', ['brewery_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_added_beer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('bar_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('brewery_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('picture_of_beer_url')
        batch_op.drop_column('description')
        batch_op.drop_column('volALC')
        batch_op.drop_column('IBUs')
        batch_op.drop_column('bjcp_style')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
