"""empty message

Revision ID: 3d06b4e5b5bc
Revises: 6860748274a6
Create Date: 2024-07-30 18:08:57.360174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d06b4e5b5bc'
down_revision = '6860748274a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=True))
        batch_op.drop_column('addres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brewery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
