"""empty message

Revision ID: be1922c22151
Revises: 3d06b4e5b5bc
Create Date: 2024-07-30 18:16:16.784794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1922c22151'
down_revision = '3d06b4e5b5bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_of_beer_url', sa.String(length=250), nullable=True))

    with op.batch_alter_table('brewery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_of_brewery_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('logo_of_brewery_url', sa.String(length=250), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_of_event_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('picture_of_event_url')

    with op.batch_alter_table('brewery', schema=None) as batch_op:
        batch_op.drop_column('logo_of_brewery_url')
        batch_op.drop_column('picture_of_brewery_url')

    with op.batch_alter_table('beer', schema=None) as batch_op:
        batch_op.drop_column('picture_of_beer_url')

    # ### end Alembic commands ###
